### PR TITLE
Compile with Windows 11

### PR DESCRIPTION
**Pull request by djibe**
Add a few instructions to compile from a naive Windows 11 (no compiler set at all).

### CODE REVIEW

**Comment by djibe** [comment]
Hi, do you need any help with this PR ?

**Comment by annieappflowy** [comment]
Hi @djibe  ,

Hope all is well with you. I'm writing to let you know we are relicensing this documentation repo from AGPL to CC BY-SA. You can find the context https://github.com/AppFlowy-IO/AppFlowy-Docs/issues/75.

You are receiving this because you’ve made significant contributions to this repo, and we are seeking consent from you to relicense your contributions, in order to adjust our licensing in the best interests of the community.

Is there a way I can send you a docusign? I'd need your name and email.
I can be found on our[ Discord ](https://discord.gg/9Q2xaN37tV)server.

Thanks,
Annie

**Comment by djibe** [comment]
Hi, thanks Annie.
I am devoted to Creative content so I agree with all your decisions.
However I contact you via Twitter if you need a real signature.

Best,
djibe

**Comment by djibe** [comment]
I can't write tou you, can you write to me on Twitter ? @RecoMedicales

**Comment by annieappflowy** [comment]
@djibe , thanks for being supportive! I followed your Twitter account but cannot msg you :(
Can you try to DM me again?

**Pull request merged**
