### PR TITLE
docs: add instructions to install emoji fonts on linux

### PR DESCRIPTION
**Pull request by richardshiue**

### CODE REVIEW

**Comment by fangykai** [comment]
As a personal preference. I believe some of the lines for the Installation instructions don't need to be changed.

**Comment by richardshiue** [comment]
> As a personal preference. I believe some of the lines for the Installation instructions don't need to be changed.

Hi, thanks for the feedback. Could you be a little bit more specific? Are you saying that certain changes are unnecessary or moved to a different PR? If so, which changes in particular?

**Comment by polypixeldev** [comment]
I think that there should also be a reference to this in the system requirements page, perhaps under a section for additional Linux requirements

**Comment by richardshiue** [comment]
Hmm, when I think of system requirements I think of more low-level stuff like the OS version, kernel version, drivers, RAM, graphics card, disk space, etc. Maybe I can move the emoji font to a more visible section, perhaps before the installation steps, in a Pre-requisites heading?

**Comment by polypixeldev** [comment]
> Hmm, when I think of system requirements I think of more low-level stuff like the OS version, kernel version, drivers, RAM, graphics card, disk space, etc. Maybe I can move the emoji font to a more visible section, perhaps before the installation steps, in a Pre-requisites heading?

Yeah, that could work. I noticed that on the "Installing on Linux" page there's already a note about glibc, so maybe it could be grouped with that?

**Comment by annieappflowy** [comment]
Hi @richardshiue , I'm going to merge this PR. Could you please resolve the conflict?

**Comment by richardshiue** [comment]
> Yeah, that could work. I noticed that on the "Installing on Linux" page there's already a note about glibc, so maybe it could be grouped with that?

Sorry for not replying immediately back then, I did make a mental note to do it. But now that I look into it, these two are on the same page and I think the emoji section large enough to deserve its own heading.

> Hi @richardshiue , I'm going to merge this PR. Could you please resolve the conflict?

Sure! I've updated the PR. Feel free to merge if everything looks okay

**Pull request merged**
